<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function openid_help($route_name, RouteMatchInterface $route_match){
	switch ($route_name){
		case 'help.page.openid': return openid_help_page();
	}
}

function openid_help_page(){
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The OpenID module allows users to log in using the OpenID single sign on service. <a href="@openid-net">OpenID</a> is a secure method for logging into many websites with a single username and password. It does not require special software, and it does not share passwords with any site to which it is associated, including the site being logged into. The main benefit to users is that they can have a single password that they can use on many websites. This means they can easily update their single password from a centralized location, rather than having to change dozens of passwords individually. For more information, see the online handbook entry for <a href="@handbook">OpenID module</a>.', array('@openid-net' => 'http://openid.net', '@handbook' => 'http://drupal.org/documentation/modules/openid')) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Logging in with OpenID') . '</dt>';
      $output .= '<dd>' . t("To log in using OpenID, a user must already have an OpenID account. Users can then create site accounts using their OpenID, assign one or more OpenIDs to an existing account, and log in using an OpenID. This lowers the barrier to registration, which helps increase the user base, and offers convenience and security to the users. Because OpenID cannot guarantee a user is legitimate, email verification is still necessary. When logging in, users are presented with the option of entering their OpenID URL, which will look like <em>myusername.openidprovider.com</em>. The site then communicates with the OpenID server, asking it to verify the identity of the user. If the user is logged into their OpenID server, the server communicates back to your site, verifying the user. If they are not logged in, the OpenID server will ask the user for their password. At no point does the site being logged into record the user's OpenID password.") . '</dd>';
      $output .= '</dl>';
	return $output;
}

/**
 * Perform discovery on a claimed ID to determine the OpenID provider endpoint.
 *
 * Discovery methods are provided by the hook_openid_discovery_method_info and
 * could be further altered using the hook_openid_discovery_method_info_alter.
 *
 * @param $claimed_id
 *   The OpenID URL to perform discovery on.
 *
 * @return
 *   The resulting discovery array from the first successful discovery method,
 *   which must contain following keys:
 *   - 'services' (required) an array of discovered services (including OpenID
 *   version, endpoint URI, etc).
 *   - 'claimed_id' (optional) new claimed identifer, found by following HTTP
 *   redirects during the services discovery.
 *   If all the discovery method fails or if no appropriate discovery method is
 *   found, FALSE is returned.
 */
function openid_discovery($claimed_id) {
	module_load_include('inc', 'openid');

	$methods = \Drupal::moduleHandler()->invokeAll('openid_discovery_method_info');
	\Drupal::moduleHandler()->alter('openid_discovery_method_info', $methods);

	// Execute each method in turn and return first successful discovery.
	foreach ($methods as $method) {
		$discovery = $method($claimed_id);
		if (!empty($discovery)) {
			return $discovery;
		}
	}
	return false;
}

/**
 * The initial step of OpenID authentication responsible for the following:
 *  - Perform discovery on the claimed OpenID.
 *  - If possible, create an association with the Provider's endpoint.
 *  - Create the authentication request.
 *  - Perform the appropriate redirect.
 *
 * @param $claimed_id The OpenID to authenticate
 * @param $return_to The endpoint to return to from the OpenID Provider
 */
function openid_begin($claimed_id, $return_to = '', $form_state = null){
	module_load_include('inc','openid');	
	
	$service = null;
	$claimed_id = openid_normalize($claimed_id);
	$discovery = openid_discovery($claimed_id);

	if (!empty($discovery['services'])) {
		$service = _openid_select_service($discovery['services']);
	}

	// Quit if the discovery result was empty or if we can't select any service.
	if (!$discovery || !$service) {
		$form_state->setErrorByName('openid_identifier',t('This openid is not known to the system'));
		return;
	}
}

